### ISSUE TITLE
How is `identifyUsers`handled?

### ISSUE THREAD

**Issue by ghost** [yogiben/meteor-mixpanel#1]
Could you please explain, how the `identifyUsers` is working? 
For example, how is the Email property passed to the events?

Thanks

**Comment by ghost** [comment]
Oh, now I see `identifyUsers` is not supported any more.

**Comment by yogiben** [comment]
Spoke with guys from Mixpanel and they advised against it.

**Comment by ghost** [comment]
Hehe, I actually dont like that name `indetifyUser`, maybe I should ask the guys tomorrow afternoon to make it dynamic ;)
